#spring:
#  cloud:
#    config:
#      name: edu-ad-boot #github上去掉yml的资源名称
#      profile: dev   #本次访问的配置项
#      label: master
#      uri: http://localhost:9966 # 去9966配置服务中心找属于自己的配置信息，靠上面的name和profile值查找


server:
  port: 8001
spring:
  application:
    name: edu-ad-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/edu_ad?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
